// leave off @2x/@3x
const images = {
  logo: require('../Images/logo.png'),
  background: require('../Images/background.png'),
  back: require('../Images/back.png'),
  iconQQ: require('../Images/icon-qq.png'),
  iconWechat: require('../Images/icon-wechat.png'),
  iconContact: require('../Images/Contact.png'),
  iconMail: require('../Images/Mail.png'),
  iconCamera: require('../Images/Camera.png'),
  iconHeart: require('../Images/Heart.png'),
  iconHeartRed: require('../Images/HeartRed.png'),
  iconHome: require('../Images/Home.png'),
  iconHomeActive: require('../Images/HomeRed.png'),
  iconSearch: require('../Images/Search.png'),
  iconSeacrhActive: require('../Images/SearchRed.png'),
  iconChat: require('../Images/Chat.png'),
  iconChatAcive: require('../Images/ChatRed.png'),
  iconProfile: require('../Images/Profile.png'),
  iconProfileActive: require('../Images/ProfileRed.png'),
  iconBands: require('../Images/Bands.png'),
  iconBandsActive: require('../Images/BandsRed.png'),
  iconSettings: require('../Images/Settings.png'),
  iconEye: require('../Images/Eye.png'),
  iconUnlocked: require('../Images/Unlocked.png'),
  iconLock: require('../Images/Lock.png'),
  iconPlus: require('../Images/Plus.png'),
  iconPlusRed: require('../Images/PlusRed.png'),
  iconPlusWhite: require('../Images/PlusWhite.png'),
  iconPlay: require('../Images/Play.png'),
  iconPlayWhite: require('../Images/PlayWhite.png'),
  iconComment: require('../Images/Comment.png'),
  iconUpload: require('../Images/Upload.png'),
  iconMagnifier: require('../Images/Magnifier.png'),
  iconImage: require('../Images/ImageIcon.png'),
  iconThreeDots: require('../Images/ThreeDots.png'),
  iconPersonRed: require('../Images/PersonRed.png'),
  iconNotification: require('../Images/Notification.png'),
  iconLibrary: require('../Images/Library.png'),
  iconBookmark: require('../Images/Bookmark.png'),
  checked: require('../Images/Checked.png'),
  uncheck: require('../Images/Uncheck.png'),
  sendButton: require('../Images/SendButton.png'),
  flyPaper: require('../Images/FlyPaper.png'),
  musicButton: require('../Images/MusicButton.png'),
  imageButton: require('../Images/ImageButton.png'),
  locationButton: require('../Images/LocationButton.png'),
  closeButton: require('../Images/CloseButton.png'),
  guitar: require('../Images/Guitar.png'),
  arrowRight: require('../Images/ArrowRight.png'),
  cameraRed: require('../Images/CameraRed.png'),
  noavatar: require('../Images/Noavatar.jpg')
}

export default images
